# Generated by https://quicktype.io

from enum import Enum
from typing import List
from datetime import datetime


class CRSProperties:
    name: str

    def __init__(self, name: str) -> None:
        self.name = name


class CRS:
    type: str
    properties: CRSProperties

    def __init__(self, type: str, properties: CRSProperties) -> None:
        self.type = type
        self.properties = properties


class GeometryType(Enum):
    MULTI_POLYGON = "MultiPolygon"


class Geometry:
    type: GeometryType
    coordinates: List[List[List[List[float]]]]

    def __init__(self, type: GeometryType, coordinates: List[List[List[List[float]]]]) -> None:
        self.type = type
        self.coordinates = coordinates


class FeatureProperties:
    objectid: int
    codigo_upl: str
    ttotal_apr_n_of_upl: float
    ttotal_apr_of_upl: float
    ttotal_deser_n_of_upl: float
    ttotal_deser_of_upl: float
    ttotal_repr_n_of_upl: float
    ttotal_repr_of_upl: float
    fecha: datetime
    shape_length: float
    shape_area: float
    nom_upl: str

    def __init__(self, objectid: int, codigo_upl: str, ttotal_apr_n_of_upl: float, ttotal_apr_of_upl: float, ttotal_deser_n_of_upl: float, ttotal_deser_of_upl: float, ttotal_repr_n_of_upl: float, ttotal_repr_of_upl: float, fecha: datetime, shape_length: float, shape_area: float, nom_upl: str) -> None:
        self.objectid = objectid
        self.codigo_upl = codigo_upl
        self.ttotal_apr_n_of_upl = ttotal_apr_n_of_upl
        self.ttotal_apr_of_upl = ttotal_apr_of_upl
        self.ttotal_deser_n_of_upl = ttotal_deser_n_of_upl
        self.ttotal_deser_of_upl = ttotal_deser_of_upl
        self.ttotal_repr_n_of_upl = ttotal_repr_n_of_upl
        self.ttotal_repr_of_upl = ttotal_repr_of_upl
        self.fecha = fecha
        self.shape_length = shape_length
        self.shape_area = shape_area
        self.nom_upl = nom_upl


class FeatureType(Enum):
    FEATURE = "Feature"


class Feature:
    type: FeatureType
    properties: FeatureProperties
    geometry: Geometry

    def __init__(self, type: FeatureType, properties: FeatureProperties, geometry: Geometry) -> None:
        self.type = type
        self.properties = properties
        self.geometry = geometry


class TasaDesercionUPLInterface:
    type: str
    name: str
    crs: CRS
    features: List[Feature]

    def __init__(self, type: str, name: str, crs: CRS, features: List[Feature]) -> None:
        self.type = type
        self.name = name
        self.crs = crs
        self.features = features
