# Generated by https://quicktype.io

from enum import Enum
from typing import List


class GeometryType(Enum):
    POLYGON = "Polygon"


class Geometry:
    type: GeometryType
    coordinates: List[List[List[float]]]

    def __init__(self, type: GeometryType, coordinates: List[List[List[float]]]) -> None:
        self.type = type
        self.coordinates = coordinates


class Cls(Enum):
    ALTA = "ALTA"
    BAJA = "BAJA"
    MEDIA = "MEDIA"


class Properties:
    cdglocalid: int
    localidad: str
    pbl2050_to: int
    clspbl205: Cls
    dsphidrica: str
    clsdsphid: Cls
    rglhidrica: str
    clsrglhid: Cls
    cldagua: str
    cls_cldagu: Cls
    shape_leng: str
    shape_area: str

    def __init__(self, cdglocalid: int, localidad: str, pbl2050_to: int, clspbl205: Cls, dsphidrica: str, clsdsphid: Cls, rglhidrica: str, clsrglhid: Cls, cldagua: str, cls_cldagu: Cls, shape_leng: str, shape_area: str) -> None:
        self.cdglocalid = cdglocalid
        self.localidad = localidad
        self.pbl2050_to = pbl2050_to
        self.clspbl205 = clspbl205
        self.dsphidrica = dsphidrica
        self.clsdsphid = clsdsphid
        self.rglhidrica = rglhidrica
        self.clsrglhid = clsrglhid
        self.cldagua = cldagua
        self.cls_cldagu = cls_cldagu
        self.shape_leng = shape_leng
        self.shape_area = shape_area


class FeatureType(Enum):
    FEATURE = "Feature"


class Feature:
    type: FeatureType
    properties: Properties
    geometry: Geometry

    def __init__(self, type: FeatureType, properties: Properties, geometry: Geometry) -> None:
        self.type = type
        self.properties = properties
        self.geometry = geometry


class VulnerabilidadAguaInterface:
    type: str
    name: str
    features: List[Feature]

    def __init__(self, type: str, name: str, features: List[Feature]) -> None:
        self.type = type
        self.name = name
        self.features = features
